---
- hosts: all
  become: true
  
  vars_files:
  - vars/main.yml

  roles:
    - base

- hosts: master
  become: true

  vars_files:
  - vars/main.yml

  roles:
  - master

- hosts: indexers
  become: true
  
  vars_files:
  - vars/main.yml
 
  roles:
  - indexer

- hosts: sh
  become: true

  vars_files:
  - vars/main.yml

  roles:
  - sh
