---
- firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ cm_ports }}"

- blockinfile:
    path: /opt/splunk/etc/system/local/server.conf
    content:  |
      [clustering]
      cluster_label = {{ cluster_label }} 
      mode = master
      pass4SymmKey = {{ secret }} 
      replication_factor = 2
  notify: restart_splunk
